spring:
  datasource:
    username: root
    password: 000000
    url: jdbc:mysql://localhost:3306/experiment?serverTimezone=GMT&useUnicode=true&characterEncoding=utf-8
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    #连接池属性
    initial-size: 15
    max-active: 100
    min-idle: 15
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    test-on-borrow: false
    test-on-return: false
    test-while-idle: true
    validation-query: SELECT 1
    validation-query-timeout: 1000
    keep-alive: true
    remove-abandoned: true
    remove-abandoned-timeout: 180
    log-abandoned: true
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat,wall,slf4j
    use-global-data-source-stat: true
    preparedStatement: true
    maxOpenPreparedStatements: 100
    connect-properties.mergeSql: true
    connect-properties.slowSqlMillis: 5000